name: Update Download Counts

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-download-counts:
    name: Update download counts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build
        run: |
          cd scripts
          npm install
          npm run build
          cd build
          for f in *.js; do mv -- "$f" "${f%.js}.cjs"; done
          ls
      - name: Run local action
        uses: ./actions/update-download-counts
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update download counts
          commit_user_name: Dredge Mod Database
